language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - pip install . --use-mirrors
  - pip install -r requirements.txt --use-mirrors
  - pip install -r tests/requirements.txt --use-mirrors
  - pip install coveralls
script:
  - nosetests --with-coverage --cover-package=algoliasearch
before_install:
  export PYTHONIOENCODING=UTF-8
after_success:
  coveralls
env:
  global:
