language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - "pip install requests"

script:
  - nosetests --with-coverage --cover-package=algoliasearch
before_install:
  export PYTHONIOENCODING=UTF-8
after_success:
  coveralls
env:
  global:
